CREATE TABLE [IF NOT EXISTS] users (
    id INTEGER(20) PRIMARY KEY AUTOINCREMENT,
    username TEXT(20) NOT NULL UNIQUE,
    password TEXT(20) NOT NULL,
    email TEXT(20) NOT NULL UNIQUE,
    created_at DATETIME(10) DEFAULT CURRENT_TIMESTAMP
    updated_at DATETIME(10) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE [IF NOT EXISTS] nutrition (
    id INTEGER(20) PRIMARY KEY AUTOINCREMENT,
    name TEXT(20) NOT NULL,
    category TEXT(20) NOT NULL,
    calories INTEGER(20) NOT NULL,
    image_url TEXT(20) NOT NULL,
    user_id INTEGER(20) NOT NULL UNIQUE,
    created_at DATETIME(10) DEFAULT CURRENT_TIMESTAMP
);